LICENSE
usr/lib/console-login-helper-messages/issuegen
usr/lib/console-login-helper-messages/motdgen
usr/share/console-login-helper-messages/profile.sh

Adds the BSD (3 clause) license with Fedora CoreOS copyright, which originally came from https://github.com/coreos/init/blob/master/LICENSE (the repository where motdgen and issuegen existed in CL before).
Checked that the license is listed in Fedora https://fedoraproject.org/wiki/Licensing:BSD?rd=Licensing/BSD#3ClauseBSD, so it doesn't look like there should be any problem.

Add BSD (3 clause) license, and comments

---

usr/libexec/console-login-helper-messages/motdgen

PRETTY_NAME is designed to be displayed to the user, and for
Fedora CoreOS it will soon be updated to a more readable string.
Fixes: #29

motdgen: display PRETTY_NAME from os-release file

---

usr/lib/tmpfiles.d/console-login-helper-messages-issuegen-tmpfiles.conf
usr/lib/tmpfiles.d/console-login-helper-messages-motdgen-tmpfiles.conf
usr/lib/tmpfiles.d/console-login-helper-messages-tmpfiles.conf

Create these directories through tmpfiles, so that
they are present once the system has booted and
can be owned by the package.

tmpfiles: create additional directories and files

---

README.md

Package already exists in Fedora and is not under review. Keep
the reviewers.md doc existing in the repository, to not break
previous links. The reviewers.md doc is also useful documentation
for manual testing.

README: remove reference to package reviewers doc

---

usr/libexec/console-login-helper-messages/issuegen

Fixes: #35 
No functional changes, contains two bugfixes. Please see commit messages for additional detail.

issuegen: do not use staged file, and fix bug in udev add/remove invocation

---

Makefile

Add starter Makefile with an `rpm` target, to build an RPM of
the repo at the current git commit `HEAD`. A bit hacky for now
with regards to versioning of the built RPM (just uses the
full git commit hash), but the versioning is sufficient for
getting a dev rpm that can be quickly installed in a test
machine.
Idea of cloning the Fedora SCM repo from: https://github.com/ostreedev/ostree/blob/383e375099067d55cf49c864684c4c7dba2c5ac1/ci/libpaprci/Makefile.dist-packaging

add Makefile for rpm

---

usr/lib/systemd/system/console-login-helper-messages-issuegen.service
usr/lib/systemd/system/console-login-helper-messages-motdgen.service

This dependency had sneaked into initial work on this
codebase:
https://github.com/coreos/console-login-helper-messages/commit/96aa0d577813bf313182f98a06a2e5c043de8970
Originally Container Linux did not include this dependency:
https://github.com/coreos/init/blob/a1dbdc3a956e82b45ae756c27ad0981afaaef60c/systemd/system/issuegen.service
At the time, it seemed sensible to include as the issuegen
service needed the IP address from the network interface.
However, the generation of the issue snippet containing the
IP address is triggered by the udev rule on appropriate
action from the interface, so there is no need to explicitly
wait on network-online.target. motdgen also does not have
a requirement for the network to be online before starting.
Previously, the dependency on …

issuegen,motdgen: remove dependency on network-online.target

---

usr/lib/systemd/system/console-login-helper-messages-issuegen.service
usr/lib/udev/rules.d/90-console-login-helper-messages-gensnippet_if.rules
usr/lib/udev/rules.d/90-console-login-helper-messages-issuegen.rules
usr/libexec/console-login-helper-messages/gensnippet_udev_if
usr/libexec/console-login-helper-messages/issuegen
usr/libexec/console-login-helper-messages/issuegen.defs

See commit messages for details.
Takes a commit split from #47 (adding the .path unit).
---
Currently not tested in the last version I pushed, but can be reviewed for feedback on the approach.

issuegen: split out udev interface generation 

---

usr/libexec/console-login-helper-messages/gensnippet_udev_if

Minor, but this file was split out in this repo recently this
year. Update its copyright notice to have 2020 instead of 2019.

gensnippet_udev_if: fix copyright date to 2020

---

usr/lib/systemd/system/console-login-helper-messages-issuegen.path
usr/lib/systemd/system/console-login-helper-messages-issuegen.service
usr/lib/systemd/system/console-login-helper-messages-motdgen.path
usr/lib/systemd/system/console-login-helper-messages-motdgen.service

With this, `-issuegen.path` and `-motdgen.path` become the only trigger to run the `-issuegen.service` and `-motdgen.service`. In my opinion, the purpose of issuegen and motdgen should be only to regenerate a MOTD/issue upon receiving new information (runtime snippets) to include in the final compiled issue/MOTD message - essentially to regenerate only when something new is dropped in `/run/console-login-helper-messages/motd.d` or `/run/console-login-helper-messages/issue.d`.
To include runtime information given by other services outside of this package, a service now need only to write into one of the directories above, and does not need to specify `After=console-login-helper-messages-issuegen.path`. The system presets to integrate console-login-helper-messages into a system are now only …

issuegen,motdgen: update unit dependencies to use only .path units

---

README-devel.md
README.md
reviewers.md

reviewers.md: fix title, remove out-of-date text
Fix title to be more general for the document, and remove text
from when previously a Vagrantfile was given in this repo for
testing, which is no longer included.
---
README: refer to reviewers.md file

Fix outdated information in reviewers doc, refer to reviewers doc from README

---

usr/lib/console-login-helper-messages/libutil.sh
usr/lib/systemd/system/console-login-helper-messages-motdgen.service
usr/libexec/console-login-helper-messages/gensnippet_udev_if
usr/libexec/console-login-helper-messages/issuegen
usr/libexec/console-login-helper-messages/motdgen

For the same reason as in https://github.com/coreos/console-login-helper-messages/pull/39
(copying the phrasing below):
With the `staged` file shared, there would be potential for two or
more processes executing `motdgen` to write to it resulting in
corrupted output, or the error in the `cat` command due to missing
file reported in #35 (comment). Currently, this is not a problem with
motdgen, but could be if `motdgen` were invoked by something like the
udev rules that invoke `issuegen`.
Instead, write the intermediate output to a variable before writing
to the final output file. This ensures only valid output is written
to the issue file shown to the terminal.
Additionally, perform code tidyups similar to those done for
`issuegen` in …

motdgen, issuegen: write staged changes to a tempfile

---

usr/libexec/console-login-helper-messages/issuegen

Fixes #53 
Also, related to https://bugzilla.redhat.com/show_bug.cgi?id=1851103
It will also help to address this comment: https://github.com/coreos/fedora-coreos-tracker/issues/279#issuecomment-632299924

issuegen: reload the agetty console upon generation of new issue snippet

---

hack/sync_to_vm.sh

So that the hacking scripts can be run from any directory in the repo.

hack: Avoid relative paths

---

Makefile

Add a symlink to link the concatentated issue file to a directory
that agetty reads from (i.e. `/etc/issue.d`). This was originally
done in the Specfile, but since we are unifying the Makefile and
Specfile to avoid multiple sources of truth, we let the `install`
target handle everything installation-related.
Also make the runtime directories
`/run/console-login-helper-messages/{issue.d, motd.d}`, since they
may not exist until `gensnippet-os-release.service` and
`gensnippet_ssh_keys.service` are run.

Makefile: add symlink and make runtime dirs

---

Makefile

Symlinks are already created by `tmpfiles.d` configuration files. 
https://github.com/coreos/console-login-helper-messages/tree/master/usr/lib/tmpfiles.d

Makefile: Remove symlinks

---

doc/manual.md
usr/lib/systemd/system/console-login-helper-messages-issuegen.path
usr/lib/systemd/system/console-login-helper-messages-issuegen.service
usr/lib/systemd/system/console-login-helper-messages-motdgen.path
usr/lib/systemd/system/console-login-helper-messages-motdgen.service

Addresses https://github.com/coreos/fedora-coreos-tracker/issues/631.
https://github.com/coreos/fedora-coreos-tracker/issues/631#issuecomment-699084342 for more context.

Remove `PathExistsGlob` option in `.path` units

---

usr/share/console-login-helper-messages/profile.sh

Update to accommodate the new output format of `systemctl list-units`.
Fixes #81

profile.sh: Update failed units' output

---

usr/libexec/console-login-helper-messages/gensnippet_if

Due to bash leaving non-matching wildcard patterns unchanged
(instead of expanding it to an empty list), if a device is not real
and does not have a subordinate device, `is_iface_backed_by_real_device()`
will get stuck in an infinite recursive loop, causing segmentation
faults.
Ignore directories that are the result of non-matching wildcard
patterns.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1884236

gensnippet_if: Fix infinite recursive function

---

usr/share/console-login-helper-messages/profile.sh

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1891920
where an error message is printed when systemd is not running.
Also switch to spaces instead of tabs.

usr/share/profile.sh: Return early if not using systemd

---

hack/run_vm.sh
hack/sync_to_vm.sh

To ensure no bad interactions between the installed CLHM and the
testing CLHM.

hack: Remove existing CLHM package on VM before rsync

---

usr/lib/console-login-helper-messages/libutil.sh

Starting from pam 1.4.0-6, pam_motd filters motd by user and group.
Currently, MOTD snippets generated by console-login-helper-messages
are allowed to be read by root only.
Change ownership to be able to be read by all users since we would
like to display this information to everyone.
Closes https://github.com/coreos/console-login-helper-messages/issues/93

libutil.sh: Allow generated MOTD files to be read by all users

---

usr/lib/tmpfiles.d/console-login-helper-messages.conf

This was mistakenly deleted in 30767e542a25f73931ef00d22c1802a1d3d5c88f.

tmpfiles: Create `/run/console-login-helper-messages`

---

tests/kola/basic/test-issue.sh
tests/kola/basic/test-motd.sh

The `issuegen.path` unit was removed in #91, but we're still checking for it.  This wasn't caught before now because CI was picking up the unit from the old version of clhm shipped in the FCOS base image.
Also, we no longer have to wait for a path unit to fire; agetty should pick up the new snippets immediately.  Drop the corresponding sleeps.
Fixes #95.

tests: drop issuegen.path status check and some unneeded sleeps

---

usr/libexec/console-login-helper-messages/gensnippet_os_release

Display attribute 39 resets the terminal to the default foreground color but doesn't reset other attributes such as background color, intensity, or reversed video.  Fedora sets `ANSI_COLOR="0;38;2;60;110;180"`, i.e. a full RGB color tuple.  In gnome-terminal this doesn't implicitly change the intensity and thus renders correctly, but in the Linux console it implicitly enables increased intensity, which is not being reset afterward.  To be safe, reset all display attributes after printing `$PRETTY_NAME`.
Fixes https://github.com/coreos/fedora-coreos-tracker/issues/750, which was exposed by https://github.com/coreos/console-login-helper-messages/pull/94.

gensnippet_os_release: fully reset ANSI attributes after ${ANSI_COLOR}

---

usr/lib/systemd/system/console-login-helper-messages-gensnippet-ssh-keys.service
usr/libexec/console-login-helper-messages/gensnippet_ssh_keys

During the major rearchitecting to switch CLHM to use directories
of upstream projects (util-linux), we accidentally dropped a
`Before=` dependency on `systemd-user-sessions.service` when
generating ssh keys snippets. This was previously done in
`issuegen.service`, but that service unit no longer exists, so we
now add the ordering dependency directly in
`gensnippet-ssh-keys.service` to ensure that we drop the files in
the necessary locations before `agetty` starts.
We also don't need the extra `agetty --reload` since we are only
writing files once, and it happens before `agetty` is started.
(This was previously required because `issuegen` supported users
dynamically dropping snippets into CLHM's private directories).

gensnippet-ssh-keys: Ensure service runs before agetty

---

.cci.jenkinsfile

The `ext.*` glob is too broad. It'll match other tests as well which may
not be defaults.

ci: constrain test glob more to run our tests

---

usr/lib/systemd/system/console-login-helper-messages-issuegen.service

An update to systemd now propagates failures up to the triggering unit.
The issuegen service is triggered by the issuegen path unit but is
conditionally run on the existence of .issue files in the issues.d
directory. If no .issue files exist in those directories, then the
issuegen service consider that a failure and propagate that failure up
to the path unit causing the path unit to fail. Ultimately,
console-login-helper-messages will no longer work because the path is
not being monitored.
Removing the condition in the issuegen service will remove the
conditional failure and thus allowing the issuegen path to continue to
monitor the directories. The downside is that the issuegen service will
run whenever any changes are made to the path directories. The
expectation is that these …

issuegen.service: workaround systemd patch

---

tests/kola/basic/data/libtest.sh
usr/share/console-login-helper-messages/profile.sh

ShellCheck was confused by the path at the begining of usr/share/console-login-helper-messages/profile.sh.
Replace it with a comment instead.

ShellCheck fixes

---

tests/kola/basic/test-motd.sh
tests/kola/basic/test-profile.sh
usr/share/console-login-helper-messages/profile.sh

This kind of output belongs better on stderr, and also can throw off
things that want to capture output from an SSH command but mistakenly
start the shell as an interactive prompt instead.

profile.sh: print failed systemd units to stderr instead
